version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: docker-node
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start  